"""empty message

Revision ID: 31730a7011ac
Revises: 
Create Date: 2020-03-07 14:13:18.479523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31730a7011ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nguoi_dung', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('nguoi_dung', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_nguoi_dung_token'), 'nguoi_dung', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nguoi_dung_token'), table_name='nguoi_dung')
    op.drop_column('nguoi_dung', 'token_expiration')
    op.drop_column('nguoi_dung', 'token')
    # ### end Alembic commands ###
