"""empty message

Revision ID: 44e4ff0b2554
Revises: 
Create Date: 2020-03-08 18:06:07.697318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e4ff0b2554'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nguoi_dung', 'token')
    op.drop_column('nguoi_dung', 'token_expiration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nguoi_dung', sa.Column('token_expiration', sa.DATETIME(), nullable=True))
    op.add_column('nguoi_dung', sa.Column('token', sa.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
