"""empty message

Revision ID: b15a557e323f
Revises: 
Create Date: 2020-03-04 15:56:09.606509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15a557e323f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loai_nguoi_dung')
    op.drop_table('nguoi_dung')
    op.drop_table('san_pham')
    op.drop_table('loai_san_pham')
    op.drop_table('khach_hang')
    op.drop_table('don_hang')
    op.drop_table('loai_bai_viet')
    op.drop_table('hoa_don')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hoa_don',
    sa.Column('ma_hoa_don', sa.INTEGER(), nullable=False),
    sa.Column('ngay_tao_hoa_don', sa.DATE(), nullable=False),
    sa.Column('ma_khach_hang', sa.INTEGER(), nullable=True),
    sa.Column('tong_tien', sa.FLOAT(), nullable=False),
    sa.Column('dia_chi_giao_hang', sa.VARCHAR(length=200), nullable=False),
    sa.Column('so_dien_thoai_nguoi_nhan', sa.VARCHAR(length=50), nullable=False),
    sa.Column('trang_thai', sa.INTEGER(), nullable=True),
    sa.Column('ghi_chu', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['ma_khach_hang'], ['khach_hang.ma_khach_hang'], ),
    sa.PrimaryKeyConstraint('ma_hoa_don')
    )
    op.create_table('loai_bai_viet',
    sa.Column('ma_loai_bai_viet', sa.INTEGER(), nullable=False),
    sa.Column('ten_loai_bai_viet', sa.VARCHAR(length=200), nullable=False),
    sa.Column('mo_ta', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('ma_loai_bai_viet')
    )
    op.create_table('don_hang',
    sa.Column('so_thu_tu', sa.INTEGER(), nullable=False),
    sa.Column('ma_hoa_don', sa.INTEGER(), nullable=True),
    sa.Column('ma_san_pham', sa.INTEGER(), nullable=True),
    sa.Column('so_luong', sa.INTEGER(), nullable=False),
    sa.Column('don_gia', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['don_gia'], ['san_pham.gia_ban'], ),
    sa.ForeignKeyConstraint(['ma_hoa_don'], ['hoa_don.ma_hoa_don'], ),
    sa.ForeignKeyConstraint(['ma_san_pham'], ['san_pham.ma_san_pham'], ),
    sa.PrimaryKeyConstraint('so_thu_tu')
    )
    op.create_table('khach_hang',
    sa.Column('ma_khach_hang', sa.INTEGER(), nullable=False),
    sa.Column('ma_nguoi_dung', sa.INTEGER(), nullable=True),
    sa.Column('ten_khach_hang', sa.VARCHAR(length=100), nullable=False),
    sa.Column('gioi_tinh', sa.VARCHAR(length=1), nullable=False),
    sa.Column('ngay_sinh', sa.DATE(), nullable=False),
    sa.Column('dia_chi', sa.VARCHAR(length=200), nullable=False),
    sa.Column('dien_thoai', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_nguoi_dung'], ['nguoi_dung.ma_nguoi_dung'], ),
    sa.PrimaryKeyConstraint('ma_khach_hang')
    )
    op.create_table('loai_san_pham',
    sa.Column('ma_loai', sa.INTEGER(), nullable=False),
    sa.Column('ten_loai', sa.VARCHAR(length=50), nullable=False),
    sa.Column('mo_ta', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ma_loai')
    )
    op.create_table('san_pham',
    sa.Column('ma_san_pham', sa.INTEGER(), nullable=False),
    sa.Column('ten_san_pham', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ma_loai', sa.INTEGER(), nullable=True),
    sa.Column('gia_ban', sa.INTEGER(), nullable=False),
    sa.Column('gia_nhap', sa.INTEGER(), nullable=False),
    sa.Column('so_luong_ton', sa.INTEGER(), nullable=False),
    sa.Column('don_vi_tinh', sa.VARCHAR(length=20), nullable=False),
    sa.Column('hinh_anh', sa.VARCHAR(length=100), nullable=False),
    sa.Column('id_sendo', sa.INTEGER(), nullable=True),
    sa.Column('sku_sendo', sa.INTEGER(), nullable=True),
    sa.Column('thuoc_tinh', sa.VARCHAR(length=200), nullable=True),
    sa.Column('mo_ta_tom_tat', sa.TEXT(), nullable=True),
    sa.Column('mo_ta_chi_tiet', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['ma_loai'], ['loai_san_pham.ma_loai'], ),
    sa.PrimaryKeyConstraint('ma_san_pham')
    )
    op.create_table('nguoi_dung',
    sa.Column('ma_nguoi_dung', sa.INTEGER(), nullable=False),
    sa.Column('ma_loai_nguoi_dung', sa.INTEGER(), nullable=True),
    sa.Column('ho_ten', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('ten_dang_nhap', sa.VARCHAR(length=64), nullable=False),
    sa.Column('mat_khau_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('ngay_dang_ky', sa.DATE(), nullable=True),
    sa.Column('lan_dang_nhap_cuoi', sa.DATETIME(), nullable=True),
    sa.Column('dang_hoat_dong', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ma_loai_nguoi_dung'], ['loai_nguoi_dung.ma_loai_nguoi_dung'], ),
    sa.PrimaryKeyConstraint('ma_nguoi_dung')
    )
    op.create_table('loai_nguoi_dung',
    sa.Column('ma_loai_nguoi_dung', sa.INTEGER(), nullable=False),
    sa.Column('ten_loai_nguoi_dung', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ma_loai_nguoi_dung')
    )
    # ### end Alembic commands ###
